[package]
name = "async-mmap"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.28.2", features = ["fs", "rt", "io-util"] }
memmap2 = "0.6.2"
futures = "0.3.28"
